//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllytaloMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lampotila
    {
        public int ID { get; set; }
        public Nullable<int> Lampotila_Huone_1 { get; set; }
        public Nullable<int> Lampotila_Huone_2 { get; set; }
        public Nullable<int> Lampotila_Huone_3 { get; set; }
        public Nullable<int> Lampotila_Huone_4 { get; set; }
    
        public virtual Valot Valot { get; set; }
    }
}
